# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     fongandrew/hydeout

# Setup
title:            prosodylab
tagline:          'prosodylab'
description:      'a research lab at mcgill'
url:              https://mchlwgnr.github.io/labpage

author:
  name:           'MW'
  url:            https://mchlwgnr.github.io/labpage/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
